#!/usr/bin/env bash

clean_generated_files() {
	cache="CMakeCache.txt cmake_install.cmake mainc maincpp $QUESTION.class cout.txt pout.txt"
	for file in $cache
	do
		if [ -f "$PWD"/"$file" ]; then
			rm "$PWD"/"$file"
		fi
	done

	dir_cache=(CMakeFiles .pytest_cache __pycache__)
	for cache in "${dir_cache[@]}"; do
		if [ -d "$cache" ]; then
			rm -rf "$cache"
		fi
	done

}

clean_generated_files
