#!/bin/bash

set -e

prob=$1


# Rename files

extensions=("c" "cpp" "java" "py")

for extension in "${extensions[@]}"; do
	if [ -f "$prob.$extension" ]; then
		mv "$prob.$extension" "$QUESTION.$extension"
	fi
done

# Update CMakeLists.txt
# ignore case sensitivity
sed "s/$QUESTION/$prob/gI" "CMakeLists.txt" > "CMakeLists.txt.tmp" && \
mv "CMakeLists.txt.tmp" "CMakeLists.txt"
