#!/bin/bash

handle_error() {
    echo "Error: $1"
    exit 1
}

backup_configs() {
    local dest_dir=""

    case "$1" in
    ubuntu) 
	    dest_dir="$HOME/.devenv/home/ubuntu" 
	    echo "Backup to ubuntu"
	    ;;
    macos) dest_dir="$HOME/.devenv/home/macos" ;;
    *) handle_error "Invalid operating system. Please specify either 'ubuntu' or 'macos'." ;;
    esac

    [ ! -d "$dest_dir" ] && mkdir -p "$dest_dir" || :

    files_to_backup=("$HOME/.zshrc" "$HOME/.p10k.zsh" "$HOME/.bashrc" "$HOME/.bash_aliases")
    config_dir=("$HOME/.config/direnv")

    for file in "${files_to_backup[@]}"; do
        [ -f "$file" ] && cp "$file" "$dest_dir" || :
    done

    for dir in "${config_dir[@]}"; do
        [ -d "$dir" ] && cp -r "$dir" "config" || :
    done

    time=$(date +"%Y-%m-%d %H:%M:%S")
    git add . && git commit -m "Backed up configuration files on $time" && git push || handle_error "Failed to commit changes to Git."

    echo "Backup completed successfully."
}

show_available_os() {
    echo "Usage: make backup <os> (os: 'ubuntu' or 'macos')"
    echo "Available OS:"
    echo "  ubuntu : Choose Ubuntu"
    echo "  macos  : Choose macOS"
}

if [ "$#" -eq 0 ]; then
    backup_configs "macos"
else
    while getopts "o:h" opt; do
        case $opt in
        o) backup_configs "$OPTARG" ;;
        h)
            show_available_os
            exit 0
            ;;
        *) handle_error "Usage: make backup <os> (os: 'ubuntu' or 'macos')" ;;
        esac
    done
fi
